server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
        - id: audit-service
          uri: lb://AUDIT-SERVICE
          predicates:
            - Path=/api/investigation/**
        - id: ai-investigation-service
          uri: lb://AI-INVESTIGATION-SERVICE
          predicates:
            - Path=/api/ai/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"

jwt:
  secret: ${JWT_SECRET:payflow-api-gateway-local-dev-secret-key}
