spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: payment-status-group
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.payflow.payment_status_service.event.PaymentCreatedEvent
        spring.json.use.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false

payment:
  kafka:
    topics:
      payment-created: payment-created-topic
      payment-status-updated: payment-status-updated-topic
      payment-stuck: payment-stuck-topic
